Loja/Loja/Models/ErrorViewModel.cs
namespace Loja.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Loja/Loja/Models/Produto.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Loja.Models
{
    [Table("Produto")]
    public class Produto
    {
        [Required]
        [Column("id")]
        [Display(Name = "Código")]
        public int Id { get; set; }

        [Required]
        [Column("nome")]
        [Display(Name = "Nome")]
        public string Nome { get; set; } = "";

        [Required]
        [Column("preco")]
        [Display(Name = "Preço")]
        public decimal Preco { get; set; }

        [Column("imagem")]
        [Display(Name = "Imagem")]
        public byte[]? Imagem { get; set; } = null;

        public bool precoValido(float preco)
        {
            try
            {
                if (preco <= 0)
                {
                    return false;
                }
                else
                {
                    return true;
                }
            }
            catch (Exception ex)
            {
                // Tratamento genérico para qualquer outra exceção
                Console.WriteLine("Erro: " + ex.Message);
                return false;
            }
        }

    }
}

Loja/Loja/Controllers/HomeController.cs
using System.Diagnostics;
using Loja.Models;
using Microsoft.AspNetCore.Mvc;

namespace Loja.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Loja/Loja/Controllers/ProdutosController.cs
using Microsoft.AspNetCore.Mvc;
using Loja.Database;
using Loja.Models;
using Loja.Repositories;
using Loja.Services;

namespace Loja.Controllers
{
    public class ProdutosController : Controller
    {
        private readonly Contexto _context;
        private readonly ProdutoRepository produtoRepository;
        private readonly ServicosImagem servicosImagem;

        public ProdutosController(Contexto context, ProdutoRepository produtoRepository, ServicosImagem servicosImagem)
        {
            _context = context;
            this.produtoRepository = produtoRepository; // inicializando o produtoRepository
            this.servicosImagem = servicosImagem; // inicializando o servicosImagem
        }

        // GET: Produtos
        public async Task<IActionResult> Index()
        {
            return View(await produtoRepository.listarProdutos());
        }

        // GET: Produtos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            return View(await produtoRepository.listarProdutosPorId(id));
        }

        // GET: Produtos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Produtos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Produto produto, IFormFile imagem)
        {

            var imagemConvertida = await servicosImagem.converteImagem(imagem);

            if (imagemConvertida == null)
            {
                return NotFound();
            }
            else
            {
                produto.Imagem = imagemConvertida;
            }

            // Remover a validação de ModelState para a propriedade Imagem
            //ModelState.Remove("Imagem");

            if (ModelState.IsValid)
            {
                if (await produtoRepository.Criar(produto))
                {
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(produto);
        }

        // GET: Produtos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {

            var produto = await produtoRepository.ProcurarPorId(id);

            if (produto == null)
            {
                return NotFound(); // Retorna 404 se o produto não for encontrado
            }

            return View(produto); // Retorna a view com o produto encontrado
        }

        // POST: Produtos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id, Nome, Preco, Imagem")] Produto produto, IFormFile imagem)
        {

            if (imagem != null)
            {
                produto.Imagem = await servicosImagem.converteImagem(imagem);
            }

            ModelState.Remove("Imagem");

            if (ModelState.IsValid)
            {
                if (await produtoRepository.Atualizar(produto))
                {
                    return RedirectToAction(nameof(Index));
                }
            }

            return View(produto);
        }

        // GET: Produtos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var produto = await produtoRepository.ProcurarPorId(id);
            if (produto == null)
            {
                return NotFound();
            }

            return View(produto);
        }

        // POST: Produtos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (await produtoRepository.Deletar(id))
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return NotFound();
            }
            
        }
    }
}

Loja/Loja/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Loja/Loja/Views/Produtos/Create.cshtml
@model Loja.Models.Produto

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Produto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Preco" class="control-label"></label>
                <input asp-for="Preco" class="form-control" />
                <span asp-validation-for="Preco" class="text-danger"></span>
            </div>

            <!-- Campo para selecionar a imagem -->
            <div class="form-group">
                <label asp-for="Imagem" class="control-label"></label>
                <input asp-for="Imagem" class="form-control" type="file" id="imagem" required />
                <div id="error-message" style="color: red; display: none;">Por favor, selecione uma imagem!</div>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" onclick="validarArquivo()" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

<script>
    function validarArquivo(event) {
      var inputFile = document.getElementById('imagem');
      var errorMessage = document.getElementById('error-message');

      // Verifique se algum arquivo foi selecionado
      if (inputFile.files.length === 0) {
        errorMessage.style.display = 'block'; // Exibe a mensagem de erro
        preventDefault();  // Impede o envio do formulário
      } else {
        errorMessage.style.display = 'none';  // Oculta a mensagem de erro
      }
    }
</script>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Loja/Loja/Views/Produtos/Delete.cshtml
@model Loja.Models.Produto

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Produto</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Preco)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Preco)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Imagem)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Imagem)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Loja/Loja/Views/Produtos/Details.cshtml
@model Loja.Models.Produto

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Produto</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Preco)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Preco)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Imagem)
        </dt>
        <dd class = "col-sm-10">
            <!-- Não use DisplayFor para Imagem -->
            @if (Model.Imagem != null && Model.Imagem.Length > 0)
            {
                <img src="data:image/png;base64,@(Convert.ToBase64String(Model.Imagem))" alt="Imagem do Produto" style="max-width: 100px; max-height: 100px;" />
            }
            else
            {
                <p>Imagem não disponível</p>
            }

        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Loja/Loja/Views/Produtos/Edit.cshtml
@model Loja.Models.Produto

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Produto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Preco" class="control-label"></label>
                <input asp-for="Preco" class="form-control" />
                <span asp-validation-for="Preco" class="text-danger"></span>
            </div>

            <!-- Campo para selecionar a imagem -->
            <div class="form-group">
                <label asp-for="Imagem" class="control-label"></label>
                <input asp-for="Imagem" class="form-control" type="file"/>
                <span asp-validation-for="Imagem" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Loja/Loja/Views/Produtos/Index.cshtml
@model IEnumerable<Loja.Models.Produto>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Preco)
            </td>
            <td>
                    <img src="data:image/png;base64,@(Convert.ToBase64String(item.Imagem))" alt="Imagem" style="max-width: 100px; max-height: 100px;" />
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Loja/Loja/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Loja</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Loja.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Loja</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Produtos" asp-action="Index">Produtos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Loja - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>